// RD1 Drum UI: the six pad levels, the master, and the soundcart
//
// The machine is plugins/RD1_Drum: six RS1 voices on six pads, and a cartridge
// slot that swaps the whole kit. Two sections, because that is what the front
// panel has -- seven levels, and the slot the cartridge goes in.
//
// The panel is hand-written rather than generated by <synth-ui> for the reason
// RGHakkuh's is: the loader is a file input, and a generated panel draws every
// parameter as a slider. The seven sliders would have been fine either way.
//
// THE SOUNDCART
//
// A cartridge is the .rs1cart tools/rs1patcher's Drumkit mode exports -- 1592
// bytes, six RS1 presets, one per pad, in the pad order kick, snare, closed hat,
// open hat, clap, tom. It replaces the kit whole. It is not merged and not
// per-pad: a file that is not a drumkit cart is refused entire, and the machine
// carries on with what it was playing. The binding parses every slot before it
// touches a voice so a broken fifth slot cannot leave five pads on the new kit
// and one on the old, and it answers with a code saying which check refused the
// file -- the sentences for those codes are in _refusal() below.
//
// What is loaded is reported by name, one line per pad. A drum machine that
// swallowed a cartridge without saying which one is not much of a machine, and
// the two NT-78 kits in data/ differ only in ways you would otherwise have to
// guess at.
//
// THE PADS
//
// Six of the page's eight pads answer. 41 and 47 are Tom Low and Tom Mid and are
// silent on this machine -- the RD-1 has one tom, at 50 -- which is said here
// rather than left as two pads that do nothing for no visible reason. The 36/38/
// 42/46/39/50 map is not a choice made on this page: it is DistrhoPluginInfo.h's
// kDrumNotes and every logue/rd1_* unit's.

/** The cartridge layout, as the binding has it. The numbers in the sentences
 *  below come from here so there is one place to change them. */
const CART_SIZE = 1592;
const CART_SLOTS = 6;

/** The pads, in slot order, with the note that reaches each. */
const PADS = [
    { slot: 0, note: 36, name: 'Kick' },
    { slot: 1, note: 38, name: 'Snare' },
    { slot: 2, note: 42, name: 'Closed hat' },
    { slot: 3, note: 46, name: 'Open hat' },
    { slot: 4, note: 39, name: 'Clap' },
    { slot: 5, note: 50, name: 'Tom' },
];

class RD1DrumUI extends HTMLElement {
    constructor() {
        super();
        this._synth = null;
        this.attachShadow({ mode: 'open' });
    }

    connectedCallback() { this.render(); this.setupListeners(); }

    get synth() { return this._synth; }

    set synth(s) {
        this._synth = s;
        if (s) s.onCartResult = (result) => this.reportCart(result);
        this.pushParameters();
    }

    setSynth(synth) { this.synth = synth; }

    /** The motion sequencer asks for this if it is here; this panel has no
     *  sequencer of its own to hand it. */
    setSequencer() {}

    /** Send the whole panel to the engine. The page's defaults win over the C
     *  ones, and here they agree: seven at 0.80 either way, which is the DPF
     *  plugin's own front panel (RD1_DrumPlugin.cpp:29-30). */
    pushParameters() {
        if (!this._synth) return;
        this.shadowRoot.querySelectorAll('[data-param]').forEach(el => {
            this._synth.setParameter(+el.dataset.param, +el.value);
        });
    }

    setupListeners() {
        const root = this.shadowRoot;

        root.querySelectorAll('[data-param]').forEach(el => {
            el.addEventListener('input', () => {
                const v = +el.value;
                const disp = root.getElementById(`v${el.dataset.param}`);
                if (disp) disp.textContent = v.toFixed(2);
                this._synth?.setParameter(+el.dataset.param, v);
            });
        });

        const loadBtn = root.getElementById('loadCartBtn');
        const fileInput = root.getElementById('cartFileInput');

        if (loadBtn && fileInput) {
            loadBtn.addEventListener('click', () => fileInput.click());

            fileInput.addEventListener('change', async (e) => {
                const file = e.target.files[0];
                if (!file) return;
                await this.loadCartFile(file);
                // Cleared so the same cartridge can be loaded again.
                fileInput.value = '';
            });
        }
    }

    async loadCartFile(file) {
        const status = this.shadowRoot.getElementById('cartStatus');

        try {
            const bytes = new Uint8Array(await file.arrayBuffer());
            if (status) {
                status.className = 'status';
                status.textContent = `Loading ${file.name}…`;
            }
            this._synth?.loadCart(bytes, file.name);
        } catch (error) {
            console.error('[RD1 UI] Could not read the cartridge:', error);
            this.reportCart({ ok: false, error: `could not read ${file.name}` });
        }
    }

    /** What the binding refused a file for. The codes are
     *  plugins/RD1_Drum/wasm_bindings.c's; see regroove_synth_load_cart(). */
    _refusal(result) {
        if (result.error) return result.error;

        switch (result.code) {
            case -1: return 'the engine refused it';
            case -2: return `not a soundcart: a drumkit cartridge is exactly ${CART_SIZE} bytes`;
            case -3: return 'not a version 1 cartridge';
            case -4: return `not a drumkit cartridge: it does not hold ${CART_SLOTS} pads`;
            case -5: return 'one of its six presets would not parse, so none of them were applied';
            default: return `refused (${result.code})`;
        }
    }

    reportCart(result) {
        const status = this.shadowRoot.getElementById('cartStatus');
        if (!status) return;

        if (!result.ok) {
            status.className = 'status bad';
            status.innerHTML = `<b>Kept the kit that was playing.</b> ${this._refusal(result)}.`;
            return;
        }

        status.className = 'status good';
        status.innerHTML =
            `<b>Soundcart loaded</b>. Six pads replaced:<br>` +
            PADS.map((pad, i) =>
                `<span class="slot">${pad.slot}</span> ${pad.name} (${pad.note}) ` +
                `<span class="loaded">${result.names[i] || 'unnamed'}</span>`
            ).join('<br>');
    }

    /** `extra` is appended inside the control, after the value readout. */
    _slider(id, label, def, extra = '') {
        return `<div class="ctrl">
          <label>${label}</label>
          <input type="range" data-param="${id}" min="0" max="1" step="0.005" value="${def}">
          <span class="val" id="v${id}">${def.toFixed(2)}</span>${extra}
        </div>`;
    }

    render() {
        this.shadowRoot.innerHTML = `
<style>
  :host { display:block; background:#141414; border:1px solid #222; border-radius:8px; padding:16px; color:#ddd; font:13px/1.4 system-ui,sans-serif; }
  h3 { margin:0 0 4px; font-size:13px; color:#e63; text-transform:uppercase; letter-spacing:2px; }
  .sub { font-size:11px; color:#666; margin-bottom:12px; }
  .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(230px,1fr)); gap:10px; }
  .section { background:#0d0d0d; border:1px solid #222; border-radius:4px; padding:10px; }
  .sec-title { font-size:10px; color:#666; text-transform:uppercase; letter-spacing:1px; margin-bottom:8px; }
  .ctrl { margin-bottom:6px; } .ctrl:last-child { margin-bottom:0; }
  label { display:block; font-size:10px; color:#888; margin-bottom:1px; }
  input[type=range] { width:100%; accent-color:#e63; }
  .val { font-size:10px; color:#e63; }
  .hint { font-size:10px; color:#555; margin-top:8px; }
  .info { font-size:11px; color:#555; margin-top:10px; }
  button.load { background:#1a1a1a; color:#ddd; border:1px solid #333; border-radius:3px; padding:6px 10px; font:12px system-ui,sans-serif; cursor:pointer; }
  button.load:hover { background:#242424; border-color:#e63; }
  input[type=file] { display:none; }
  .status { font-size:11px; color:#777; margin-top:8px; line-height:1.6; }
  .status.good { color:#8a8; } .status.bad { color:#e63; }
  .slot { display:inline-block; min-width:12px; color:#666; }
  .loaded { color:#ddd; }
</style>

<h3>RD1 Drum: RS-1 Drum Machine</h3>
<div class="sub">Six RS-1 voices, one per pad, playing the factory kit until a soundcart replaces it. Pads <b>36</b> kick, <b>38</b> snare, <b>42</b> closed hat, <b>46</b> open hat, <b>39</b> clap, <b>50</b> tom. Tom Low (41) and Tom Mid (47) are silent: this machine has one tom, and it is at 50.</div>

<div class="grid">
  <div class="section">
    <div class="sec-title">Pads</div>
    ${PADS.map(p => this._slider(p.slot, `${p.name}: pad ${p.note}`, 0.80)).join('\n    ')}
    <div class="hint">A pad level takes that drum out of the sum and nothing else.
      Six pads landing together are held inside full scale by the soft clip after
      the mix, not by these.</div>
  </div>

  <div class="section">
    <div class="sec-title">Soundcart</div>
    <button class="load" id="loadCartBtn">📂 Load soundcart</button>
    <input type="file" id="cartFileInput" accept=".rs1cart">
    <div class="hint">A drumkit cartridge: six RS-1 presets, one per pad, in pad
      order. It replaces the whole kit; this is not a per-pad loader, and a file
      that is not a drumkit cartridge is refused rather than half-applied.</div>
    <div class="status" id="cartStatus">Factory kit. ${PADS.map(p => p.name).join(', ')}.</div>
  </div>

  <div class="section">
    <div class="sec-title">Master</div>
    ${this._slider(6, 'Master: the whole machine', 0.80)}
    <div class="hint">After the soft clip, so turning it down does not un-clip
      anything.</div>
  </div>
</div>

<div class="info">
  Every pad strikes its voice at one note whatever the pad was: an RS-1 preset
  carries its own pitch, so a pad is that preset played once. A hit decays on its
  own: there is no note-off, and a cartridge cannot change that.
</div>`;
    }
}

customElements.define('rd1-drum-ui', RD1DrumUI);
export default RD1DrumUI;
