/**
 * RG909: the sample-based TR-909
 *
 * The drumlogue unit's instrument: synth/synth_tr909.c playing the machine's own
 * recordings (44100 Hz, compiled into data/tr909/tr909_samples.c), with the
 * twenty-two controls the hardware puts on its front panel. The page and the
 * hardware are the same engine and the same values, which is the whole point of
 * this class -- the previous `rg909` on the page was a different engine entirely
 * (plugins/RG909_Drum, a synthesized full kit) and was neither of the two 909s
 * this repository builds.
 *
 * It is not RGHakkuh. That one is two synthesized voices and seven knobs; this
 * one is ten sampled voices and twenty-two. They are different machines and the
 * page carries both.
 *
 * A note-off IS forwarded here, unlike on the other three drum components. The
 * engine has tr909_synth_note_off(), which fades the drum out rather than leaving
 * it to ring, and it exists because this page is also played from a keyboard: a
 * crash left sounding over the notes played after the key came up is heard as a
 * mistake. A drum machine has no use for it; a keyboard does.
 *
 * The panel is generated by <synth-ui> from getParameterInfo() below -- twenty-two
 * sliders is past the point where a hand-written panel is worth keeping in step.
 */

import { SynthRegistry } from '../synth-registry.js';

class RG909Synth {
    constructor(audioContext) {
        this.audioContext = audioContext;
        this.workletNode = null;
        this.masterGain = null;
        this.wasmModule = null;
        this.wasmInstance = null;
        this.wasmError = null;
        this.isInitialized = false;

        this.parameterInfo = RG909Synth.getParameterInfo();
    }

    /**
     * The twenty-two knobs, in the machine's own panel order, at the positions the
     * hardware powers up at (logue/rg909_drum/header.c). Values are the panel's
     * 0..100 with scale:'normalized', so the slider shows the number the hardware
     * shows and synth-ui sends it divided by a hundred -- which is what the
     * drumlogue does too.
     *
     * These are load-bearing rather than decorative. The worklet means to seed
     * parameters from the engine's own defaults, but the function it would call is
     * never mapped (web/replugged/worklets/synth-worklet-processor.js, the dead
     * block around line 483), so the panel's numbers are the only ones the page
     * ever has. They are the engine's own defaults: tr909_synth_param_default()
     * returns 0.6875 for every level, which is 69 here, and the drumlogue's header
     * says 69 as well.
     *
     * TR909_PARAM_MASTER is the engine's twenty-third parameter and is not here.
     * Its default is 1.0 (0 dB) and the unit leaves it there: the drumlogue has a
     * volume of its own, so a second one under this panel would only be in the way.
     */
    static getParameterInfo() {
        return [
            // Bass drum
            { index: 0, name: 'BD Tune', type: 'float', group: 'Bass Drum',
              min: 0, max: 100, default: 0, scale: 'normalized',
              description: 'Pitch sweep speed' },
            { index: 1, name: 'BD Attack', type: 'float', group: 'Bass Drum',
              min: 0, max: 100, default: 100, scale: 'normalized',
              description: 'Click level at the front of the hit' },
            { index: 2, name: 'BD Decay', type: 'float', group: 'Bass Drum',
              min: 0, max: 100, default: 50, scale: 'normalized',
              description: 'Body decay' },
            { index: 3, name: 'BD Level', type: 'float', group: 'Bass Drum',
              min: 0, max: 100, default: 69, scale: 'normalized',
              description: 'Bass drum level (-6 dB at 69)' },

            // Snare
            { index: 4, name: 'SD Tune', type: 'float', group: 'Snare',
              min: 0, max: 100, default: 50, scale: 'normalized',
              description: 'Tuning, +/- half an octave' },
            { index: 5, name: 'SD Tone', type: 'float', group: 'Snare',
              min: 0, max: 100, default: 100, scale: 'normalized',
              description: 'Noise decay: the snare body' },
            { index: 6, name: 'SD Snappy', type: 'float', group: 'Snare',
              min: 0, max: 100, default: 100, scale: 'normalized',
              description: 'Noise level: the snares under the head' },
            { index: 7, name: 'SD Level', type: 'float', group: 'Snare',
              min: 0, max: 100, default: 69, scale: 'normalized',
              description: 'Snare level' },

            // Toms
            { index: 8, name: 'Tom Tune', type: 'float', group: 'Toms',
              min: 0, max: 100, default: 50, scale: 'normalized',
              description: 'Shared by all three toms' },
            { index: 9, name: 'Tom Decay', type: 'float', group: 'Toms',
              min: 0, max: 100, default: 100, scale: 'normalized',
              description: 'Shared by all three toms' },
            { index: 10, name: 'Low Tom', type: 'float', group: 'Toms',
              min: 0, max: 100, default: 69, scale: 'normalized',
              description: 'Low tom level' },
            { index: 11, name: 'Mid Tom', type: 'float', group: 'Toms',
              min: 0, max: 100, default: 69, scale: 'normalized',
              description: 'Mid tom level' },
            { index: 12, name: 'High Tom', type: 'float', group: 'Toms',
              min: 0, max: 100, default: 69, scale: 'normalized',
              description: 'High tom level' },

            // Percussion
            { index: 13, name: 'Rimshot', type: 'float', group: 'Percussion',
              min: 0, max: 100, default: 69, scale: 'normalized',
              description: 'Rimshot level' },
            { index: 14, name: 'Clap', type: 'float', group: 'Percussion',
              min: 0, max: 100, default: 69, scale: 'normalized',
              description: 'Hand clap level' },

            // Hi-hats
            { index: 15, name: 'CH Decay', type: 'float', group: 'Hi-Hats',
              min: 0, max: 100, default: 0, scale: 'normalized',
              description: 'Closed hi-hat decay: shortest at 0' },
            { index: 16, name: 'OH Decay', type: 'float', group: 'Hi-Hats',
              min: 0, max: 100, default: 50, scale: 'normalized',
              description: 'Open hi-hat decay' },
            { index: 17, name: 'HiHat Level', type: 'float', group: 'Hi-Hats',
              min: 0, max: 100, default: 69, scale: 'normalized',
              description: 'Both hi-hats: on the original they are one channel, so striking either chokes the other' },

            // Cymbals
            { index: 18, name: 'Cym Tune', type: 'float', group: 'Cymbals',
              min: 0, max: 100, default: 50, scale: 'normalized',
              description: 'Shared by the crash and the ride' },
            { index: 19, name: 'Crash', type: 'float', group: 'Cymbals',
              min: 0, max: 100, default: 69, scale: 'normalized',
              description: 'Crash cymbal level' },
            { index: 20, name: 'Ride', type: 'float', group: 'Cymbals',
              min: 0, max: 100, default: 69, scale: 'normalized',
              description: 'Ride cymbal level' },

            // Global
            { index: 21, name: 'Accent', type: 'float', group: 'Global',
              min: 0, max: 100, default: 50, scale: 'normalized',
              description: 'How much hits above velocity 100 are lifted' },
        ];
    }

    async initialize() {
        try {
            console.log('[RG909] Loading WASM module...');

            const paths = SynthRegistry.getPaths();
            // Cache-busted, for the reason spelled out in rgstorm-synth.js. The
            // samples make this pair much the largest in web/rfxsynths/, so a
            // stale copy is both the most likely and the slowest to notice.
            const v = '?v=' + Date.now();
            const wasmJsPath = paths.wasm + 'rg909-synth.js' + v;
            const wasmBinaryPath = paths.wasm + 'rg909-synth.wasm' + v;

            const [jsResponse, wasmResponse] = await Promise.all([
                fetch(wasmJsPath),
                fetch(wasmBinaryPath)
            ]);

            if (!jsResponse.ok || !wasmResponse.ok) {
                throw new Error('Failed to fetch WASM files');
            }

            const jsCode = await jsResponse.text();
            const wasmBytes = await wasmResponse.arrayBuffer();

            console.log('[RG909] WASM files loaded');

            await this.audioContext.audioWorklet.addModule(
                paths.worklets + 'synth-worklet-processor.js' + v);

            this.masterGain = this.audioContext.createGain();
            this.masterGain.gain.value = 1.0;

            this.workletNode = new AudioWorkletNode(
                this.audioContext, 'synth-worklet-processor', {
                    outputChannelCount: [2]
                });

            await new Promise((resolve, reject) => {
                const timeout = setTimeout(() => reject(new Error('Worklet timeout')), 5000);

                this.workletNode.port.onmessage = (event) => {
                    if (event.data.type === 'needWasm') {
                        this.workletNode.port.postMessage({
                            type: 'wasmBytes',
                            data: {
                                jsCode: jsCode,
                                wasmBytes: wasmBytes,
                                engineId: 0,   // one engine per module
                                // The context's rate. The engine resamples its
                                // own 44100 Hz sample set to whatever this is, so
                                // the number decides every drum's pitch and
                                // length. The worklet would default to 48000.
                                sampleRate: this.audioContext.sampleRate
                            }
                        });
                    } else if (event.data.type === 'ready') {
                        clearTimeout(timeout);
                        resolve();
                    } else if (event.data.type === 'error') {
                        clearTimeout(timeout);
                        reject(new Error(event.data.data.message));
                    }
                };
            });

            this.workletNode.connect(this.masterGain);

            this.isInitialized = true;
            console.log('[RG909] Initialized successfully');
            return true;

        } catch (error) {
            console.error('[RG909] Initialization error:', error);
            this.wasmError = error.message;
            return false;
        }
    }

    /**
     * The General MIDI kit, which is the engine's own map: 36 kick, 38 snare,
     * 37 rim, 39 clap, 41/43 low tom, 45/47 mid tom, 48/50 high tom, 42 closed
     * hat, 44 pedal hat, 46 open hat, 49/52/55/57 crash, 51/53/59 ride. A kick,
     * snare or tom note has a second note that is the same drum struck soft --
     * the machine's weak/strong pair, and it does not sound like the note beside
     * it. Velocity 0 plays nothing, as on the machine.
     */
    noteOn(note, velocity = 100) {
        if (!this.isInitialized) return;
        this.workletNode?.port.postMessage({
            type: 'noteOn',
            data: { note, velocity }
        });
    }

    /**
     * What the drum pads, the channel-10 MIDI branch and playKeyboardNote all
     * call; the classes this replaces each carried this alias.
     */
    triggerDrum(note, velocity = 100) {
        this.noteOn(note, velocity);
    }

    /**
     * Forwarded, unlike on the other three drum components: the engine fades the
     * drum out rather than leaving it to ring, which is what a keyboard needs and
     * a drum machine does not. See the class comment.
     */
    noteOff(note) {
        if (!this.isInitialized) return;
        this.workletNode?.port.postMessage({
            type: 'noteOff',
            data: { note }
        });
    }

    setParameter(paramId, value) {
        if (!this.isInitialized) return;
        this.workletNode?.port.postMessage({
            type: 'setParameter',
            data: { index: paramId, value: value }
        });
    }

    allNotesOff() {
        if (!this.isInitialized) return;
        this.workletNode?.port.postMessage({ type: 'allNotesOff' });
    }

    setSpeakerOutput(enabled) {
        if (this.masterGain) {
            this.masterGain.gain.value = enabled ? 1.0 : 0.0;
        }
    }

    destroy() {
        if (this.workletNode) {
            this.workletNode.disconnect();
            this.workletNode = null;
        }
        this.isInitialized = false;
        console.log('[RG909] Destroyed');
    }
}

SynthRegistry.register({
    id: 'rg909',
    name: 'RG909',
    displayName: 'RG909: TR-909 Drum Machine',
    description: 'Sample-based TR-909: ten voices, the machine\'s own recordings, 22 panel controls',
    engineId: 10,   // one engine per module, unused by the binding
    class: RG909Synth,
    category: 'drum',
    wasmFiles: {
        js: 'rg909-synth.js',
        wasm: 'rg909-synth.wasm'
    },
    getParameterInfo: RG909Synth.getParameterInfo
});

export { RG909Synth };
