// RGHakkuh UI: the pq4 drumlogue's nine knobs, in its three pages
//
// The unit is logue/rghakkuh_pq4_drumlogue: page 1 the EQ's three band levels,
// page 2 its two sweepable frequencies, page 3 the drive, the two drum levels
// and the EQ routing. This panel is those three pages as three columns, with the
// page-3 routing control on the end, so a drumlogue player reads it the way they
// already read the machine.
//
// The parameter indices are the unit's own -- 0, 1, 2, 4, 5, 8, 9, 10, 11 -- and
// not a compacted 0..8. Slots 3, 6 and 7 are blank on the machine because BD
// TUNE was removed from slot 6 and its neighbours were left where they were, and
// the binding keeps that layout, so the number under a slider here is the slot
// number there.
//
// Assigning `synth` pushes all nine, so the page opens on the panel rather than
// on whatever the C create happened to set -- they agree, both being the unit's
// init table, but the panel is what the player can see and so it is the one that
// decides.
//
// The two frequency sliders carry the Hz their position lands on, because
// fx_pq4's sweep is logarithmic and 0.50 alone says nothing about where it sits.
// 0.5 is the centre of each band: 400 Hz for MID, 2 kHz for HI.
//
// EQ ROUTE is a <select> because it is not a level: 0 the whole drum, 1 the kick
// alone, 2 the snare alone. As a slider it would read as "how much", which is
// exactly the wrong idea -- there is no amount of routing, and the machine
// offers the three names as a list too. The binding takes it as the index it is
// and ignores anything outside 0..2.
//
// The panel is hand-written rather than generated by <synth-ui> because of that
// select; a generated panel draws every parameter as a slider. The other three
// drum panels, which have no such control, are generated.

class RGHakkuhUI extends HTMLElement {
    constructor() {
        super();
        this._synth = null;
        this.attachShadow({ mode: 'open' });
    }

    connectedCallback() { this.render(); this.setupListeners(); }

    get synth() { return this._synth; }

    set synth(s) {
        this._synth = s;
        this.pushParameters();
    }

    setSynth(synth) { this.synth = synth; }

    /** Send the whole panel to the engine. The page's defaults win over the C ones. */
    pushParameters() {
        if (!this._synth) return;
        this.shadowRoot.querySelectorAll('[data-param]').forEach(el => {
            this._synth.setParameter(+el.dataset.param, +el.value);
        });
    }

    setSequencer() {}

    setupListeners() {
        const root = this.shadowRoot;

        root.querySelectorAll('[data-param]').forEach(el => {
            el.addEventListener('input', () => {
                const v = +el.value;
                const disp = root.getElementById(`v${el.dataset.param}`);
                if (disp) disp.textContent = v.toFixed(2);
                const hz = root.getElementById(`h${el.dataset.param}`);
                if (hz) hz.textContent = this._hzText(+el.dataset.param, v);
                this._synth?.setParameter(+el.dataset.param, v);
            });
        });
    }

    /** The Hz a frequency slider's position lands on: fx_pq4's own curve. Only
     *  the two frequency indices have one; anything else returns ''. */
    _hzText(index, v) {
        const band = RGHakkuhUI.BANDS[index];
        if (!band) return '';
        const [lo, hi] = band;
        return `${Math.round(lo * Math.pow(hi / lo, v))} Hz`;
    }

    /** The MID and HI bands' sweeps, in Hz by parameter index, exactly as
     *  effects/fx_pq4.c has them: sixteen times across the band in both cases. */
    static BANDS = { 4: [100, 1600], 5: [500, 8000] };

    /** `extra` is appended inside the control, after the value readout. The two
     *  frequency sliders use it for the Hz their position lands on, because the
     *  sweep is logarithmic and a bare 0.50 says nothing about where it sits;
     *  those spans carry an id and are refreshed on input. */
    _slider(id, label, def, extra = '') {
        return `<div class="ctrl">
          <label>${label}</label>
          <input type="range" data-param="${id}" min="0" max="1" step="0.005" value="${def}">
          <span class="val" id="v${id}">${def.toFixed(2)}</span>${extra}
        </div>`;
    }

    _freqSlider(id, label) {
        return this._slider(id, label, 0.50,
            ` <span class="hz" id="h${id}">${this._hzText(id, 0.50)}</span>`);
    }

    render() {
        this.shadowRoot.innerHTML = `
<style>
  :host { display:block; background:#141414; border:1px solid #222; border-radius:8px; padding:16px; color:#ddd; font:13px/1.4 system-ui,sans-serif; }
  h3 { margin:0 0 4px; font-size:13px; color:#e63; text-transform:uppercase; letter-spacing:2px; }
  .sub { font-size:11px; color:#666; margin-bottom:12px; }
  .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(230px,1fr)); gap:10px; }
  .section { background:#0d0d0d; border:1px solid #222; border-radius:4px; padding:10px; }
  .sec-title { font-size:10px; color:#666; text-transform:uppercase; letter-spacing:1px; margin-bottom:8px; }
  .ctrl { margin-bottom:6px; } .ctrl:last-child { margin-bottom:0; }
  label { display:block; font-size:10px; color:#888; margin-bottom:1px; }
  input[type=range] { width:100%; accent-color:#e63; }
  select { width:100%; background:#1a1a1a; color:#ddd; border:1px solid #333; border-radius:3px; padding:3px; font:12px system-ui,sans-serif; }
  .val { font-size:10px; color:#e63; }
  .hz { font-size:10px; color:#8a8; }
  .hint { font-size:10px; color:#555; margin-top:8px; }
  .info { font-size:11px; color:#555; margin-top:10px; }
</style>

<h3>RGHakkuh: 909 Kick &amp; Snare, PQ-4</h3>
<div class="sub">Two drums, driven: the synthesized 909 kick and snare behind DRIVE and the PQ-4 parametric EQ. Pad <b>36</b> is the kick, <b>38</b> the snare, <b>60</b> and <b>64</b> both. Every other note is silent: this is the Hakkuh instrument, not the full kit.</div>

<div class="grid">
  <div class="section">
    <div class="sec-title">Page 1: EQ band levels</div>
    ${this._slider(0, 'Low level: kill .. boost', 0.50)}
    ${this._slider(1, 'Mid level: kill .. boost', 0.50)}
    ${this._slider(2, 'High level: kill .. boost', 0.50)}
    <div class="hint">0.50 is flat; below is a cut, above a boost, ±18 dB.</div>
  </div>
  <div class="section">
    <div class="sec-title">Page 2: EQ frequencies</div>
    ${this._freqSlider(4, 'Mid frequency: where the mid band sits')}
    ${this._freqSlider(5, 'High frequency: where the high band sits')}
    <div class="hint">The low band's corner is fixed. An 8 kHz presence shelf is
      in the EQ but not on the panel: inaudible on a bass kick.</div>
  </div>
  <div class="section">
    <div class="sec-title">Page 3: drive, levels, routing</div>
    ${this._slider(8, 'Drive: clean .. saturated (kick only)', 0.50)}
    ${this._slider(9, 'BD level: the finished kick', 0.70)}
    ${this._slider(10, 'SD level: the snare', 1.00)}
    <div class="ctrl">
      <label>EQ route: what the EQ hears</label>
      <select data-param="11">
        <option value="0" selected>BD+SD</option>
        <option value="1">BD</option>
        <option value="2">SD</option>
      </select>
    </div>
  </div>
</div>

<div class="info">
  The snare never passes through the drive (on the machine the drive belongs to
  the bass drum), so DRIVE changes the kick and leaves the snare alone. Velocity
  reaches the snare only: the kick ignores it (its own engine discards it), which
  is why a soft click on pad 36 sounds the same as a hard one.
</div>`;
    }
}

customElements.define('rghakkuh-ui', RGHakkuhUI);
export default RGHakkuhUI;
